// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/eva01/backup-guardian/domain"
	mock "github.com/stretchr/testify/mock"
)

// SyncRunsReadWriter is an autogenerated mock type for the SyncRunsReadWriter type
type SyncRunsReadWriter struct {
	mock.Mock
}

// CreateSyncRun provides a mock function with given fields: run
func (_m *SyncRunsReadWriter) CreateSyncRun(run *domain.SyncRun) (*domain.SyncRun, error) {
	ret := _m.Called(run)

	if len(ret) == 0 {
		panic("no return value specified for CreateSyncRun")
	}

	var r0 *domain.SyncRun
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.SyncRun) (*domain.SyncRun, error)); ok {
		return rf(run)
	}
	if rf, ok := ret.Get(0).(func(*domain.SyncRun) *domain.SyncRun); ok {
		r0 = rf(run)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SyncRun)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.SyncRun) error); ok {
		r1 = rf(run)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncRun provides a mock function with given fields: selector
func (_m *SyncRunsReadWriter) GetSyncRun(selector *domain.SyncRunSelector) (*domain.SyncRun, error) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncRun")
	}

	var r0 *domain.SyncRun
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.SyncRunSelector) (*domain.SyncRun, error)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(*domain.SyncRunSelector) *domain.SyncRun); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SyncRun)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.SyncRunSelector) error); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSyncRuns provides a mock function with given fields: selector
func (_m *SyncRunsReadWriter) ListSyncRuns(selector *domain.SyncRunsSelector) ([]*domain.SyncRun, error) {
	ret := _m.Called(selector)

	if len(ret) == 0 {
		panic("no return value specified for ListSyncRuns")
	}

	var r0 []*domain.SyncRun
	var r1 error
	if rf, ok := ret.Get(0).(func(*domain.SyncRunsSelector) ([]*domain.SyncRun, error)); ok {
		return rf(selector)
	}
	if rf, ok := ret.Get(0).(func(*domain.SyncRunsSelector) []*domain.SyncRun); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.SyncRun)
		}
	}

	if rf, ok := ret.Get(1).(func(*domain.SyncRunsSelector) error); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSyncRun provides a mock function with given fields: run
func (_m *SyncRunsReadWriter) UpdateSyncRun(run *domain.SyncRun) error {
	ret := _m.Called(run)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSyncRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.SyncRun) error); ok {
		r0 = rf(run)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSyncRunsReadWriter creates a new instance of SyncRunsReadWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncRunsReadWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SyncRunsReadWriter {
	mock := &SyncRunsReadWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
