// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type SyncRun struct {
	ID               string         `json:"id"`
	JobName          string         `json:"job_name"`
	Status           string         `json:"status"`
	StartedAt        sql.NullTime   `json:"started_at"`
	FinishedAt       sql.NullTime   `json:"finished_at"`
	ErrorMessage     sql.NullString `json:"error_message"`
	FilesTransferred sql.NullInt64  `json:"files_transferred"`
	BytesTransferred sql.NullInt64  `json:"bytes_transferred"`
	CreatedAt        time.Time      `json:"created_at"`
}
