// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error)
	GetSyncRun(ctx context.Context, id string) (SyncRun, error)
	ListSyncRuns(ctx context.Context, arg ListSyncRunsParams) ([]SyncRun, error)
	UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) error
}

var _ Querier = (*Queries)(nil)
