// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_runs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (id, job_name, status, started_at)
VALUES (?, ?, 'running', ?)
RETURNING id, job_name, status, started_at, finished_at, error_message, files_transferred, bytes_transferred, created_at
`

type CreateSyncRunParams struct {
	ID        string       `json:"id"`
	JobName   string       `json:"job_name"`
	StartedAt sql.NullTime `json:"started_at"`
}

func (q *Queries) CreateSyncRun(ctx context.Context, arg CreateSyncRunParams) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, createSyncRun, arg.ID, arg.JobName, arg.StartedAt)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.JobName,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.FilesTransferred,
		&i.BytesTransferred,
		&i.CreatedAt,
	)
	return i, err
}

const getSyncRun = `-- name: GetSyncRun :one
SELECT id, job_name, status, started_at, finished_at, error_message, files_transferred, bytes_transferred, created_at FROM sync_runs
WHERE id = ?
`

func (q *Queries) GetSyncRun(ctx context.Context, id string) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, getSyncRun, id)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.JobName,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
		&i.FilesTransferred,
		&i.BytesTransferred,
		&i.CreatedAt,
	)
	return i, err
}

const listSyncRuns = `-- name: ListSyncRuns :many
SELECT id, job_name, status, started_at, finished_at, error_message, files_transferred, bytes_transferred, created_at FROM sync_runs
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSyncRunsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSyncRuns(ctx context.Context, arg ListSyncRunsParams) ([]SyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listSyncRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncRun{}
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.JobName,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
			&i.FilesTransferred,
			&i.BytesTransferred,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSyncRun = `-- name: UpdateSyncRun :exec
UPDATE sync_runs
SET status = ?,
    finished_at = ?,
    error_message = ?,
    files_transferred = ?,
    bytes_transferred = ?
WHERE id = ?
`

type UpdateSyncRunParams struct {
	Status           string         `json:"status"`
	FinishedAt       sql.NullTime   `json:"finished_at"`
	ErrorMessage     sql.NullString `json:"error_message"`
	FilesTransferred sql.NullInt64  `json:"files_transferred"`
	BytesTransferred sql.NullInt64  `json:"bytes_transferred"`
	ID               string         `json:"id"`
}

func (q *Queries) UpdateSyncRun(ctx context.Context, arg UpdateSyncRunParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncRun,
		arg.Status,
		arg.FinishedAt,
		arg.ErrorMessage,
		arg.FilesTransferred,
		arg.BytesTransferred,
		arg.ID,
	)
	return err
}
