// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	result "github.com/eva01/backup-guardian/runner/result"
	mock "github.com/stretchr/testify/mock"
)

// RcloneExecutor is an autogenerated mock type for the RcloneExecutor type
type RcloneExecutor struct {
	mock.Mock
}

// Sync provides a mock function with given fields: ctx, source, dest
func (_m *RcloneExecutor) Sync(ctx context.Context, source string, dest string) (*result.RcloneResult, error) {
	ret := _m.Called(ctx, source, dest)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 *result.RcloneResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*result.RcloneResult, error)); ok {
		return rf(ctx, source, dest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *result.RcloneResult); ok {
		r0 = rf(ctx, source, dest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*result.RcloneResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, source, dest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRcloneExecutor creates a new instance of RcloneExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRcloneExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *RcloneExecutor {
	mock := &RcloneExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
